### ISSUE TITLE
pure release -pom 发布失败

### ISSUE THREAD

**Issue by qaz3954179** [hefangshi/fis-pure-demo#4]
...........fis release -pom [ /home/yongqi: symbol lookup error: /usr/lib/node_modules/fis-pure/node_modules/fis/node_modules/fis-optimizer-png-compressor/node_modules/node-pngcrush/lib/linux/x64/0.12.0/png_compress.node: undefined symbol: _ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_

node 版本
v0.11.14

**Comment by hefangshi** [comment]
不支持node 11，在安装node 10或者node 12后重新安装fis-pure
